services:
  # Frontend Service
  frontend:
    build:
      context: ./frontend # directory containing dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      VITE_APP_API_URL: http://localhost:3001
    depends_on:
      - backend

  # Backend Service
  backend:
    build:
      context: ./backend # directory containing dockerfile
    ports:
      - "3001:3001"
    volumes:
      - /app/node_modules
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydatabase
      - TZ=America/Vancouver
    develop:
      watch:
        - path: ./backend/src
          action: sync+restart
          target: /app/src
        - action: rebuild
          path: ./backend/package.json
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    command:
      - '--logpath'
      - '/var/log/mongodb/mongod.log'
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: