/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: LowPolyBoy (https://sketchfab.com/lowPolyBoy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/box-aquarium-3e2c1da5770546c89d2a934eb4ef83b9
Title: Box Aquarium
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import aquariumScene from "../../assets/3d/furniture/aquarium.glb";

const Aquarium = (props) => {
  const groupRef = useRef();
  const { nodes, materials, animations } = useGLTF(aquariumScene);
  const { actions, mixer } = useAnimations(animations, groupRef);

  // Set overall model scale here
  const overallScale = [6, 6, 4];

  // Activate all animations when component mounts
  useEffect(() => {
    console.log('Available animations:', Object.keys(actions));
    
    // Play all available animations
    Object.keys(actions).forEach((actionName) => {
      const action = actions[actionName];
      if (action) {
        action.play();
        console.log(`Playing animation: ${actionName}`);
      }
    });

    // Clean up animations on unmount
    return () => {
      Object.keys(actions).forEach((actionName) => {
        actions[actionName]?.stop();
      });
    };
  }, [actions]);

  return (
    <group {...props} ref={groupRef} scale={overallScale} position={[0, 0, 0]}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="Circle010_0"
                position={[-0.807, 0.803, -0.272]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0}>
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials.Color}
                />
              </group>
              <group
                name="Circle011_1"
                position={[-0.807, 0.803, -0.272]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0}>
                <mesh
                  name="Object_6"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_6.geometry}
                  material={materials.Color}
                />
              </group>
              <group
                name="Circle012_2"
                position={[-0.807, 0.803, -0.272]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0}>
                <mesh
                  name="Object_8"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_8.geometry}
                  material={materials.Color}
                />
              </group>
              <group
                name="fish045_3"
                position={[-0.803, 0.755, 0.595]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={0.609}>
                <mesh
                  name="Object_10"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_10.geometry}
                  material={materials.fish}
                />
              </group>
              <group
                name="fish046_4"
                position={[0.393, 0.699, 0.595]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={0.523}>
                <mesh
                  name="Object_12"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_12.geometry}
                  material={materials.fish}
                />
              </group>
              <group
                name="fish048_5"
                position={[0.765, 0.681, 0.595]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={0.609}>
                <mesh
                  name="Object_14"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_14.geometry}
                  material={materials.fish}
                />
              </group>
              <group
                name="fish049_6"
                position={[0.636, 0.975, 0.595]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.609}>
                <mesh
                  name="Object_16"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_16.geometry}
                  material={materials.fish}
                />
              </group>
              <group
                name="fish051_7"
                position={[0.334, 0.489, 0.595]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.609}>
                <mesh
                  name="Object_18"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_18.geometry}
                  material={materials.fish}
                />
              </group>
              <group
                name="fish052_8"
                position={[-0.107, 0.208, 0.595]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.609}>
                <mesh
                  name="Object_20"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_20.geometry}
                  material={materials.fish}
                />
              </group>
              <group
                name="fish053_9"
                position={[-0.494, 0.5, 0.595]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.609}>
                <mesh
                  name="Object_22"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_22.geometry}
                  material={materials.fish}
                />
              </group>
              <group
                name="fish054_10"
                position={[-0.111, 0.844, 0.595]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={1.06}>
                <mesh
                  name="Object_24"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_24.geometry}
                  material={materials.fish}
                />
              </group>
              <group
                name="fish040_11"
                position={[-0.892, 0.542, 0.226]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.431}>
                <mesh
                  name="Object_26"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_26.geometry}
                  material={materials['fish.001']}
                />
              </group>
              <group
                name="fish041_12"
                position={[-0.683, 0.957, 0.226]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={0.431}>
                <mesh
                  name="Object_28"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_28.geometry}
                  material={materials['fish.001']}
                />
              </group>
              <group
                name="fish042_13"
                position={[-0.361, 0.624, 0.226]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.432}>
                <mesh
                  name="Object_30"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_30.geometry}
                  material={materials['fish.001']}
                />
              </group>
              <group
                name="fish043_14"
                position={[0.233, 0.99, 0.226]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={0.431}>
                <mesh
                  name="Object_32"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_32.geometry}
                  material={materials['fish.001']}
                />
              </group>
              <group
                name="fish044_15"
                position={[-0.036, 0.63, 0.226]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.431}>
                <mesh
                  name="Object_34"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_34.geometry}
                  material={materials['fish.001']}
                />
              </group>
              <group
                name="fish035_16"
                position={[-0.704, 0.781, -0.109]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.287}>
                <mesh
                  name="Object_36"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_36.geometry}
                  material={materials['fish.002']}
                />
              </group>
              <group
                name="fish036_17"
                position={[-0.614, 0.683, -0.109]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.287}>
                <mesh
                  name="Object_38"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_38.geometry}
                  material={materials['fish.002']}
                />
              </group>
              <group
                name="fish037_18"
                position={[-0.524, 0.762, -0.109]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.287}>
                <mesh
                  name="Object_40"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_40.geometry}
                  material={materials['fish.002']}
                />
              </group>
              <group
                name="fish038_19"
                position={[-0.48, 0.7, -0.109]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.287}>
                <mesh
                  name="Object_42"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_42.geometry}
                  material={materials['fish.002']}
                />
              </group>
              <group
                name="fish039_20"
                position={[-0.586, 0.844, -0.109]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.287}>
                <mesh
                  name="Object_44"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_44.geometry}
                  material={materials['fish.002']}
                />
              </group>
              <group
                name="fish030_21"
                position={[-0.084, 0.493, -0.404]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.351}>
                <mesh
                  name="Object_46"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_46.geometry}
                  material={materials['fish.003']}
                />
              </group>
              <group
                name="fish031_22"
                position={[0.251, 0.669, -0.404]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={0.351}>
                <mesh
                  name="Object_48"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_48.geometry}
                  material={materials['fish.003']}
                />
              </group>
              <group
                name="fish032_23"
                position={[0.277, 0.401, -0.404]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.351}>
                <mesh
                  name="Object_50"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_50.geometry}
                  material={materials['fish.003']}
                />
              </group>
              <group
                name="fish033_24"
                position={[0.639, 0.716, -0.404]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={0.351}>
                <mesh
                  name="Object_52"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_52.geometry}
                  material={materials['fish.003']}
                />
              </group>
              <group
                name="fish034_25"
                position={[0.858, 0.855, -0.404]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.351}>
                <mesh
                  name="Object_54"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_54.geometry}
                  material={materials['fish.003']}
                />
              </group>
              <group
                name="fish001_26"
                position={[-0.627, 0.563, -0.221]}
                rotation={[Math.PI / 2, -0.026, 0]}
                scale={0.24}>
                <mesh
                  name="Object_56"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_56.geometry}
                  material={materials['fish.004']}
                />
              </group>
              <group
                name="fish002_27"
                position={[-0.3, 0.404, -0.221]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.24}>
                <mesh
                  name="Object_58"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_58.geometry}
                  material={materials['fish.004']}
                />
              </group>
              <group
                name="fish027_28"
                position={[0.531, 0.489, -0.221]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={0.19}>
                <mesh
                  name="Object_60"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_60.geometry}
                  material={materials['fish.004']}
                />
              </group>
              <group
                name="fish028_29"
                position={[-0.045, 0.353, -0.221]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.24}>
                <mesh
                  name="Object_62"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_62.geometry}
                  material={materials['fish.004']}
                />
              </group>
              <group
                name="fish029_30"
                position={[-0.893, 0.677, -0.221]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.24}>
                <mesh
                  name="Object_64"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_64.geometry}
                  material={materials['fish.004']}
                />
              </group>
              <group name="Box_71">
                <mesh
                  name="Object_66"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_66.geometry}
                  material={materials.lpb_box}
                />
                <mesh
                  name="Object_67"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_67.geometry}
                  material={materials.Color}
                />
                <mesh
                  name="Object_68"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_68.geometry}
                  material={materials.Icons}
                />
                <mesh
                  name="Object_69"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_69.geometry}
                  material={materials.ColorGradient}
                />
                <group
                  name="coral3_31"
                  position={[-0.217, 0.481, -0.284]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.349}>
                  <mesh
                    name="Object_71"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_71.geometry}
                    material={materials.coral3}
                  />
                </group>
                <group
                  name="coral3001_32"
                  position={[0.89, 0.759, -0.284]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.381}>
                  <mesh
                    name="Object_73"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_73.geometry}
                    material={materials.coral3}
                  />
                </group>
                <group
                  name="coral3002_33"
                  position={[-0.83, 0.968, -0.56]}
                  rotation={[Math.PI / 2, -0.066, 0]}
                  scale={0.309}>
                  <mesh
                    name="Object_75"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_75.geometry}
                    material={materials.coral4}
                  />
                </group>
                <group
                  name="coral3003_34"
                  position={[0.832, 0.932, -0.56]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.309}>
                  <mesh
                    name="Object_77"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_77.geometry}
                    material={materials.coral4}
                  />
                </group>
                <group
                  name="coral3004_35"
                  position={[0.177, 0.464, -0.284]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.309}>
                  <mesh
                    name="Object_79"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_79.geometry}
                    material={materials.coral3}
                  />
                </group>
                <group
                  name="coral3005_36"
                  position={[0.29, 0.607, -0.56]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.309}>
                  <mesh
                    name="Object_81"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_81.geometry}
                    material={materials.coral4}
                  />
                </group>
                <group
                  name="coral3006_37"
                  position={[-0.291, 0.603, -0.56]}
                  rotation={[Math.PI / 2, -0.409, 0]}
                  scale={0.309}>
                  <mesh
                    name="Object_83"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_83.geometry}
                    material={materials.coral4}
                  />
                </group>
                <group
                  name="coral3007_38"
                  position={[-0.505, 0.599, -0.284]}
                  rotation={[Math.PI / 2, -0.237, 0]}
                  scale={0.309}>
                  <mesh
                    name="Object_85"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_85.geometry}
                    material={materials.coral3}
                  />
                </group>
                <group
                  name="coral3008_39"
                  position={[-0.809, 0.742, -0.284]}
                  rotation={[Math.PI / 2, -0.297, 0]}
                  scale={0.309}>
                  <mesh
                    name="Object_87"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_87.geometry}
                    material={materials.coral3}
                  />
                </group>
                <group
                  name="coral3009_40"
                  position={[0.578, 0.564, -0.284]}
                  rotation={[Math.PI / 2, 0.308, 0]}
                  scale={0.309}>
                  <mesh
                    name="Object_89"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_89.geometry}
                    material={materials.coral3}
                  />
                </group>
                <group
                  name="coral3010_41"
                  position={[-0.008, 0.455, -0.284]}
                  rotation={[Math.PI / 2, -0.149, 0]}
                  scale={0.212}>
                  <mesh
                    name="Object_91"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_91.geometry}
                    material={materials.coral3}
                  />
                </group>
                <group
                  name="coral3011_42"
                  position={[-0.101, 0.645, -0.56]}
                  rotation={[Math.PI / 2, -0.066, 0]}
                  scale={0.309}>
                  <mesh
                    name="Object_93"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_93.geometry}
                    material={materials.coral4}
                  />
                </group>
                <group
                  name="coral3012_43"
                  position={[0.489, 0.733, -0.56]}
                  rotation={[Math.PI / 2, 0.095, 0]}
                  scale={0.309}>
                  <mesh
                    name="Object_95"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_95.geometry}
                    material={materials.coral4}
                  />
                </group>
                <group
                  name="coral3013_44"
                  position={[-0.536, 0.783, -0.56]}
                  rotation={[Math.PI / 2, -0.176, 0]}
                  scale={0.309}>
                  <mesh
                    name="Object_97"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_97.geometry}
                    material={materials.coral4}
                  />
                </group>
                <group
                  name="fish003_49"
                  position={[0.439, 0.382, 0.427]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.381}>
                  <mesh
                    name="mesh_45"
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_45.geometry}
                    material={materials.coral1}
                    morphTargetDictionary={nodes.mesh_45.morphTargetDictionary}
                    morphTargetInfluences={nodes.mesh_45.morphTargetInfluences}
                  />
                </group>
                <group
                  name="fish005_50"
                  position={[-0.867, 0.692, 0.046]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.465}>
                  <mesh
                    name="mesh_46"
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_46.geometry}
                    material={materials.coral2}
                    morphTargetDictionary={nodes.mesh_46.morphTargetDictionary}
                    morphTargetInfluences={nodes.mesh_46.morphTargetInfluences}
                  />
                </group>
                <group
                  name="fish007_51"
                  position={[-0.833, 0.461, 0.428]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.471}>
                  <mesh
                    name="Object_103"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_103.geometry}
                    material={materials.coral1}
                  />
                </group>
                <group
                  name="fish009_52"
                  position={[0.605, 0.486, 0.046]}
                  rotation={[Math.PI / 2, 0.078, 0]}
                  scale={0.288}>
                  <mesh
                    name="Object_105"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_105.geometry}
                    material={materials.coral2}
                  />
                </group>
                <group
                  name="fish011_53"
                  position={[-0.519, 0.462, 0.046]}
                  rotation={[Math.PI / 2, -0.145, 0]}
                  scale={0.288}>
                  <mesh
                    name="Object_107"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_107.geometry}
                    material={materials.coral2}
                  />
                </group>
                <group
                  name="fish012_54"
                  position={[-0.135, 0.26, 0.422]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.196}>
                  <mesh
                    name="Object_109"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_109.geometry}
                    material={materials.coral1}
                  />
                </group>
                <group
                  name="fish013_55"
                  position={[0.866, 0.467, 0.422]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.357}>
                  <mesh
                    name="Object_111"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_111.geometry}
                    material={materials.coral1}
                  />
                </group>
                <group
                  name="fish014_56"
                  position={[0.648, 0.378, 0.422]}
                  rotation={[Math.PI / 2, 0.141, 0]}
                  scale={0.474}>
                  <mesh
                    name="Object_113"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_113.geometry}
                    material={materials.coral1}
                  />
                </group>
                <group
                  name="fish016_57"
                  position={[0.239, 0.31, 0.422]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.356}>
                  <mesh
                    name="Object_115"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_115.geometry}
                    material={materials.coral1}
                  />
                </group>
                <group
                  name="fish017_58"
                  position={[-0.304, 0.325, 0.423]}
                  rotation={[Math.PI / 2, -0.055, Math.PI]}
                  scale={0.304}>
                  <mesh
                    name="Object_117"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_117.geometry}
                    material={materials.coral1}
                  />
                </group>
                <group
                  name="fish018_59"
                  position={[0.127, 0.276, 0.422]}
                  rotation={[Math.PI / 2, -0.038, 0]}
                  scale={0.14}>
                  <mesh
                    name="Object_119"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_119.geometry}
                    material={materials.coral1}
                  />
                </group>
                <group
                  name="fish019_60"
                  position={[0.331, 0.347, 0.046]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.243}>
                  <mesh
                    name="Object_121"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_121.geometry}
                    material={materials.coral2}
                  />
                </group>
                <group
                  name="fish020_61"
                  position={[-0.375, 0.456, 0.046]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.296}>
                  <mesh
                    name="Object_123"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_123.geometry}
                    material={materials.coral2}
                  />
                </group>
                <group
                  name="fish021_62"
                  position={[0.168, 0.355, 0.046]}
                  rotation={[Math.PI / 2, 0.02, 0]}
                  scale={0.265}>
                  <mesh
                    name="Object_125"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_125.geometry}
                    material={materials.coral2}
                  />
                </group>
                <group
                  name="fish022_63"
                  position={[-0.606, 0.509, 0.046]}
                  rotation={[Math.PI / 2, -0.074, 0]}
                  scale={0.265}>
                  <mesh
                    name="Object_127"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_127.geometry}
                    material={materials.coral2}
                  />
                </group>
                <group
                  name="fish026_64"
                  position={[-0.097, 0.33, 0.046]}
                  rotation={[Math.PI / 2, -0.08, 0]}
                  scale={0.178}>
                  <mesh
                    name="Object_129"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_129.geometry}
                    material={materials.coral2}
                  />
                </group>
                <group
                  name="pl1_65"
                  position={[-0.81, 0.291, 0.782]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={[0.487, 0.487, 0.598]}>
                  <mesh
                    name="mesh_61"
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_61.geometry}
                    material={materials.plant1}
                    morphTargetDictionary={nodes.mesh_61.morphTargetDictionary}
                    morphTargetInfluences={nodes.mesh_61.morphTargetInfluences}
                  />
                </group>
                <group
                  name="Plane_66"
                  position={[0, 0.232, 0.73]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={[0.984, 1, 0.169]}>
                  <mesh
                    name="Object_133"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_133.geometry}
                    material={materials.Color}
                  />
                </group>
                <group
                  name="Plane001_67"
                  position={[0, 0.232, 0.429]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={[0.984, 1, 0.169]}>
                  <mesh
                    name="Object_135"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_135.geometry}
                    material={materials.Color}
                  />
                </group>
                <group
                  name="Plane002_68"
                  position={[0, 0.232, 0.05]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={[0.984, 1, 0.169]}>
                  <mesh
                    name="Object_137"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_137.geometry}
                    material={materials.Color}
                  />
                </group>
                <group
                  name="Plane003_69"
                  position={[0, 0.232, -0.278]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={[0.984, 1, 0.169]}>
                  <mesh
                    name="Object_139"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_139.geometry}
                    material={materials.Color}
                  />
                </group>
                <group
                  name="Plane004_70"
                  position={[0, 0.232, -0.555]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={[0.984, 1, 0.169]}>
                  <mesh
                    name="Object_141"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_141.geometry}
                    material={materials.Color}
                  />
                </group>
              </group>
              <group
                name="Circle001_72"
                position={[-0.197, 0.513, -0.281]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0}>
                <mesh
                  name="Object_143"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_143.geometry}
                  material={materials.Color}
                />
              </group>
              <group
                name="Circle002_73"
                position={[-0.197, 0.513, -0.281]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0}>
                <mesh
                  name="Object_145"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_145.geometry}
                  material={materials.Color}
                />
              </group>
              <group
                name="Circle006_74"
                position={[-0.197, 0.513, -0.281]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0}>
                <mesh
                  name="Object_147"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_147.geometry}
                  material={materials.Color}
                />
              </group>
              <group
                name="Circle003_75"
                position={[0.597, 0.524, 0.048]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0}>
                <mesh
                  name="Object_149"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_149.geometry}
                  material={materials.Color}
                />
              </group>
              <group
                name="Circle004_76"
                position={[0.597, 0.524, 0.048]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0}>
                <mesh
                  name="Object_151"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_151.geometry}
                  material={materials.Color}
                />
              </group>
              <group
                name="Circle005_77"
                position={[0.597, 0.524, 0.048]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0}>
                <mesh
                  name="Object_153"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_153.geometry}
                  material={materials.Color}
                />
              </group>
              <group
                name="Circle007_78"
                position={[0.162, 0.395, 0.048]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0}>
                <mesh
                  name="Object_155"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_155.geometry}
                  material={materials.Color}
                />
              </group>
              <group
                name="Circle008_79"
                position={[0.162, 0.395, 0.048]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0}>
                <mesh
                  name="Object_157"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_157.geometry}
                  material={materials.Color}
                />
              </group>
              <group
                name="Circle009_80"
                position={[0.162, 0.395, 0.048]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0}>
                <mesh
                  name="Object_159"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_159.geometry}
                  material={materials.Color}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(aquariumScene);
export default Aquarium;
