/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import bedScene from "../../assets/3d/furniture/bed1.glb";

const Bed1 = (props) => {
  const groupRef = useRef();
  const { nodes, materials } = useGLTF(bedScene);
  const overallScale = [60, 60, 60];

  return (
    <group ref={groupRef} {...props} scale={overallScale}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Right_Pillow.geometry}
        material={materials.Blue}
        position={[0.004, 0, 0.002]}
        rotation={[3.138, -0.046, -3.058]}
        scale={[-0.072, -0.013, -0.072]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Left_Pillow.geometry}
        material={materials.Blue}
        rotation={[3.138, -0.046, -3.058]}
        scale={[-0.072, -0.013, -0.072]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mattress001.geometry}
        material={materials.White}
        rotation={[3.138, -0.046, -3.058]}
        scale={[-0.072, -0.013, -0.072]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Blanket001.geometry}
        material={materials.Blue}
        rotation={[3.138, -0.046, -3.058]}
        scale={[-0.072, -0.013, -0.072]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bedframe.geometry}
        material={materials.Tan}
        rotation={[3.138, -0.046, -3.058]}
        scale={[-0.072, -0.013, -0.072]}
      />
    </group>
  );
};

useGLTF.preload(bedScene);
export default Bed1;
