/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import deskChairScene from "../../assets/3d/furniture/deskChair1.glb";

const DeskChair1 = (props) => {
  const groupRef = useRef();
  const { nodes, materials } = useGLTF(deskChairScene);

  // Set overall model scale here
  const overallScale = [50, 50, 50];

  return (
    <group {...props} dispose={null} ref={groupRef} scale={overallScale}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube101.geometry}
        material={materials.blanc}
        position={[0, 0, -0.116]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <group
        position={[0, 0, -0.116]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh152.geometry}
          material={materials.brun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh152_1.geometry}
          material={materials.blanc}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh152_2.geometry}
          material={materials.vert}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube104.geometry}
        material={materials.noir}
        position={[0, 0, -0.116]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube125.geometry}
        material={materials.blanc}
        position={[0, 0, -0.116]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube126.geometry}
        material={materials.blanc}
        position={[0, 0, -0.116]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube138.geometry}
        material={materials.blanc}
        position={[0, 0, -0.116]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube139.geometry}
        material={materials.turquoise}
        position={[0, 0, -0.116]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube140.geometry}
        material={materials.bleu}
        position={[0, 0, -0.116]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCylinder66.geometry}
        material={materials.noir}
        position={[0, 0, -0.116]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCylinder67.geometry}
        material={materials.noir}
        position={[0, 0, -0.116]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCylinder70.geometry}
        material={materials.turquoise}
        position={[0.006, -0.003, -0.129]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pSphere137.geometry}
        material={materials.light}
        position={[-0.359, 0.355, -0.089]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.012}
      />
      <group
        position={[0, 0, -0.116]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh219.geometry}
          material={materials.noir}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh219_1.geometry}
          material={materials.musique}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh12.geometry}
        material={materials.beige}
        position={[-0.166, 0, -0.132]}
        rotation={[-Math.PI / 2, 0, -2.324]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube163.geometry}
        material={materials.beige}
        position={[-0.098, 0.243, 0.098]}
        rotation={[-1.569, 0.184, -1.58]}
        scale={[-0.118, -0.006, -0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube167.geometry}
        material={materials.noir}
        position={[-0.294, 0.241, 0.045]}
        rotation={[-Math.PI / 2, 0, 3.06]}
        scale={[-0.045, -0.153, -0.025]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube168.geometry}
        material={materials.turquoise}
        position={[-0.29, 0.229, 0.181]}
        rotation={[-Math.PI / 2, 0, -2.993]}
        scale={[-0.055, -0.055, -0.001]}
      />
    </group>
  );
};

useGLTF.preload(deskChairScene);
export default DeskChair1;
