/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";

import deskScene from "../../assets/3d/furniture/deskChair1.glb";

const deskChair1 = (props) => {
  const groupRef = useRef();
  const { nodes, materials } = useGLTF(deskScene);

  // Set overall model scale here
  const overallScale = [65, 65, 65];

  return (
    <group ref={groupRef} {...props} scale={overallScale}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube101.geometry}
        material={materials.blanc}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <group rotation={[-Math.PI / 2, 0, -Math.PI]} scale={-0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh152.geometry}
          material={materials.brun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh152_1.geometry}
          material={materials.blanc}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh152_2.geometry}
          material={materials.vert}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube104.geometry}
        material={materials.noir}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.012}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube125.geometry}
        material={materials.blanc}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube126.geometry}
        material={materials.blanc}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube138.geometry}
        material={materials.blanc}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube139.geometry}
        material={materials.turquoise}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube140.geometry}
        material={materials.bleu}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCylinder66.geometry}
        material={materials.noir}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCylinder67.geometry}
        material={materials.noir}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCylinder70.geometry}
        material={materials.turquoise}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pSphere137.geometry}
        material={materials.light}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.012}
      />
      <group rotation={[-Math.PI / 2, 0, -Math.PI]} scale={-0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh219.geometry}
          material={materials.noir}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh219_1.geometry}
          material={materials.musique}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh12.geometry}
        material={materials.beige}
        position={[-0.006, -0.003, -0.004]}
        rotation={[-Math.PI / 2, 0, -2.324]}
        scale={-0.011}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube163.geometry}
        material={materials.beige}
        position={[-0.006, -0.003, -0.004]}
        rotation={[-1.569, 0.184, -1.58]}
        scale={[-0.128, -0.007, -0.032]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube167.geometry}
        material={materials.noir}
        rotation={[-Math.PI / 2, 0, 3.06]}
        scale={[-0.045, -0.153, -0.025]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube168.geometry}
        material={materials.turquoise}
        rotation={[-Math.PI / 2, 0, -2.993]}
        scale={[-0.055, -0.055, -0.001]}
      />
    </group>
  );
};

export default deskChair1;
