/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import fanScene from "../../assets/3d/furniture/fan1.glb";

const Fan1 = (props) => {
  const groupRef = useRef();
  const { nodes, materials } = useGLTF(fanScene);

  // Set overall model scale here
  const overallScale = [0.4, 0.4, 0.4];

  return (
    <group ref={groupRef} {...props} scale={overallScale}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials["YELLOWIS WHITE"]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.968}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Back_cover.geometry}
          material={materials["YELLOWIS WHITE"]}
          rotation={[-Math.PI, -1.501, -1.571]}
          scale={[0.073, 0.089, 0.089]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Blades.geometry}
          material={materials["YELLOWIS WHITE"]}
          rotation={[0, 0.698, 0]}
          scale={0.474}
        />
        <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.63, 0.63, 0.484]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001.geometry}
            material={materials["YELLOWIS WHITE"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001_1.geometry}
            material={materials["YELLOWIS WHITE"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001_2.geometry}
            material={materials["YELLOWIS WHITE"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Buttons.geometry}
          material={materials["GRAE WHITE"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Clicker.geometry}
          material={materials["GRAE WHITE"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.086, 0.321, 0.086]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cover_rim.geometry}
          material={materials["YELLOWIS WHITE"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.994}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fan_rod.geometry}
          material={materials["METAL BLACK"]}
          scale={[0.083, 1.714, 0.083]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Front_cover.geometry}
          material={materials["YELLOWIS WHITE"]}
          rotation={[Math.PI, 1.501, Math.PI / 2]}
          scale={[0.073, 0.089, 0.089]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Middle_neck.geometry}
          material={materials["GRAE WHITE"]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Neck.geometry}
          material={materials["YELLOWIS WHITE"]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder.geometry}
            material={materials["LIGHT DARK WHITE"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_1.geometry}
            material={materials.BLACK}
          />
        </group>
      </mesh>
    </group>
  );
};

useGLTF.preload(fanScene);
export default Fan1;
