/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import frameScene from "../../assets/3d/furniture/frame1.glb";

const Frame1 = (props) => {
  const groupRef = useRef();
  const { nodes, materials } = useGLTF(frameScene);

  // Set overall model scale here
  const overallScale = [5, 5, 5];

  return (
    <group ref={groupRef} {...props} scale={overallScale}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Frame.geometry}
        material={materials["Material.001"]}
        position={[2.828, 1.507, 0.489]}
        rotation={[0, 0, -Math.PI]}
        scale={[-1, -1, -0.126]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Photo.geometry}
        material={materials.Photo}
        position={[2.828, 1.507, 0.489]}
        rotation={[0, 0, -Math.PI]}
        scale={[-1, -1, -0.126]}
      />
    </group>
  );
};

useGLTF.preload(frameScene);
export default Frame1;
