/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: JessSwynn (https://sketchfab.com/JessSwynn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gunther-e91561eda80944cf8d6f34e2462c2866
Title: Gunther
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import guntherScene from "../../assets/3d/furniture/gunther.glb";

const Gunther = (props) => {
  const groupRef = useRef();
  const { nodes, materials } = useGLTF(guntherScene);

  // Set overall model scale here
  const overallScale = [0.015, 0.015, 0.015];

  return (
    <group {...props} ref={groupRef} scale={overallScale} position={[0, 0, 0]}>
      <group position={[0, 91.861, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 78.744, 100]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_Material002_0.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_Material003_0.geometry}
          material={materials['Material.003']}
        />
      </group>
      <group position={[182.805, 57.286, -122.81]} rotation={[2.542, 1.529, -2.542]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_Material002_0.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_Material003_0.geometry}
          material={materials['Material.003']}
        />
      </group>
      <group
        position={[80.322, 221.096, 127.556]}
        rotation={[0.474, 0.361, -0.497]}
        scale={[67.049, 49.994, 46.995]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_Material002_0.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_Material003_0.geometry}
          material={materials['Material.003']}
        />
      </group>
      <group
        position={[120.305, 29.255, 105.887]}
        rotation={[0.073, 0.38, -0.043]}
        scale={[73.734, 54.978, 51.68]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_Material002_0.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_Material003_0.geometry}
          material={materials['Material.003']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle_Material002_0.geometry}
        material={materials['Material.002']}
        position={[59.132, 331.847, 95.293]}
        rotation={[-0.348, 0.159, 0.137]}
        scale={19.177}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_Material002_0.geometry}
        material={materials['Material.002']}
        position={[23.562, 308.69, 115.478]}
        rotation={[0.162, 0.075, -0.01]}
        scale={[27.498, 26.752, 42.16]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001_Material002_0.geometry}
        material={materials['Material.002']}
        position={[0.952, 294.462, 118.366]}
        rotation={[0.213, -0.119, 0.081]}
        scale={[20.245, 19.696, 31.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder_Material003_0.geometry}
        material={materials['Material.003']}
        position={[146.09, 329.726, 51.495]}
        rotation={[-1.072, 1.141, -0.623]}
        scale={[-95.721, 94.667, 118.982]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DryFlower1_DryFlower1_0.geometry}
        material={materials.DryFlower1}
        position={[0, 526.834, 0]}
        scale={100}
      />
    </group>
  )
}

useGLTF.preload(guntherScene);
export default Gunther;
