/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Vivek Thakur🌴 (https://sketchfab.com/anothervivek)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/labubu-box-47e103b28d0045ab90872b73c642d371
Title: Labubu Box
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import labubuScene from "../../assets/3d/furniture/labubu.glb";

const Labubu = (props) => {
  const groupRef = useRef();
  const { nodes, materials } = useGLTF(labubuScene);

  // Set overall model scale here
  const overallScale = [1, 1, 1];

  return (
    <group {...props} ref={groupRef} scale={overallScale} position={[0, 1.5, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Material}
        scale={[0.76, 1.641, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.Material}
        position={[0, 1.641, 1]}
        scale={[0.76, 1.641, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.Material}
        position={[0, 1.641, -1]}
        scale={[0.76, 1.641, 1]}
      />
    </group>
  )
}

useGLTF.preload(labubuScene);
export default Labubu;
