/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Hafiene (https://sketchfab.com/ahmedhafiene98)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cute-rabbit-a92db0809f3f447f876d643ac38bf48b
Title: Cute Rabbit
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import rabbitScene from "../../assets/3d/furniture/rabbit.glb";

const Rabbit = (props) => {
  const groupRef = useRef();
  const { nodes, materials } = useGLTF(rabbitScene);

  // Set overall model scale here
  const overallScale = [1, 1, 1];

  return (
    <group {...props} ref={groupRef} scale={overallScale} position={[0, 0, 0]}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['3enin_Material002_0'].geometry}
          material={materials['Material.002']}
          position={[-600.969, 0, -72.659]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['5cham_Material008_0'].geometry}
          material={materials['Material.008']}
          position={[-602.551, 6.354, 158.509]}
          rotation={[-1.802, 0, Math.PI]}
          scale={[-20.153, 2.887, 20.153]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bdan_Material007_0.geometry}
          material={materials['Material.007']}
          position={[-600.969, -237.532, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[141.61, 113.94, 117.583]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sa9in_Material007_0.geometry}
          material={materials['Material.007']}
          position={[-600.969, -18.019, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.iden__Material007_0.geometry}
          material={materials['Material.007']}
          position={[-600.969, 0, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.kerch_2_Material008_0.geometry}
          material={materials['Material.008']}
          position={[-599.747, -237.532, 2.697]}
          rotation={[-1.544, 0, 0]}
          scale={[141.61, 113.94, 117.583]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['5doud001_Material008_0'].geometry}
          material={materials['Material.008']}
          position={[-600.969, 0, -7.028]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ras_Material007_0.geometry}
          material={materials['Material.007']}
          position={[-600.969, -5.235, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[232.094, 159.02, 176.568]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wedhnen__1_Material007_0.geometry}
          material={materials['Material.007']}
          position={[-600.969, 0, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ba3bous_Material007_0.geometry}
          material={materials['Material.007']}
          position={[-600.969, -281.811, -113.805]}
          scale={32.045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.fom_Material004_0.geometry}
          material={materials['Material.004']}
          position={[-602.524, -22.055, 160.208]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[13.013, 12.811, 9.515]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wedhnen__1001_Material007_0.geometry}
          material={materials['Material.007']}
          position={[-763.943, -7.2, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wedhnen__1002_Material008_0.geometry}
          material={materials['Material.008']}
          position={[-565.625, 87.05, 11.396]}
          rotation={[-Math.PI / 2, 0.007, 0]}
          scale={52.281}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wedhnen__1003_Material008_0.geometry}
          material={materials['Material.008']}
          position={[-725.336, 91.583, 8.452]}
          rotation={[-Math.PI / 2, 0.007, 0]}
          scale={52.281}
        />
      </group>
    </group>
  )
}

useGLTF.preload(rabbitScene);
export default Rabbit;
