/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import rugScene from "../../assets/3d/furniture/rug1.glb";

const Rug1 = (props) => {
  const groupRef = useRef();
  const { nodes, materials } = useGLTF(rugScene);

  // Set overall model scale here
  const overallScale = [7, 7, 7];

  return (
    <group ref={groupRef} {...props} scale={overallScale}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Outer.geometry}
        material={materials.Green}
        scale={[1.904, 1, 1.221]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Center.geometry}
        material={materials.Blue}
        scale={[1.904, 1, 1.221]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Between.geometry}
        material={materials.Orange}
        scale={[1.904, 1, 1.221]}
      />
    </group>
  );
};

useGLTF.preload(rugScene);
export default Rug1;
