/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: LortDigital (https://sketchfab.com/LortDigital)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-dining-table-74eec744589d41ff8dc62c2b9856b37b
Title: Low Poly Dining Table
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import tableScene from "../../assets/3d/furniture/table1.glb";

const Table = (props) => {
  const groupRef = useRef();
  const { nodes, materials } = useGLTF(tableScene);

  // Set overall model scale here
  const overallScale = [0.03, 0.03, 0.03];

  return (
    <group {...props} ref={groupRef} scale={overallScale} position={[0, 0, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_table_0.geometry}
        material={materials.table}
        position={[0, 290.584, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[381.222, 209.3, 186.984]}
      />
    </group>
  )
}

useGLTF.preload(tableScene);
export default Table;
