/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: YAN YIN (https://sketchfab.com/yinyan1298)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/trash-can-2e9e6e123b3a40ffa0bc4336f237c94d
Title: trash can
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import trashScene from "../../assets/3d/furniture/trash.glb";

const Trash = (props) => {
  const groupRef = useRef();
  const { nodes, materials } = useGLTF(trashScene);

  // Set overall model scale here
  const overallScale = [0.06, 0.06, 0.06];

  return (
    <group {...props} ref={groupRef} scale={overallScale} position={[0, 0, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cone001__0.geometry}
        material={materials['Scene_-_Root']}
        position={[-19.92, 0, -3.984]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['������001__0'].geometry}
        material={materials['Scene_-_Root']}
        position={[-19.92, 0, -3.984]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload(trashScene);
export default Trash;
