/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import warpPipeScene from "../../assets/3d/furniture/warpPipe.glb";

const warpPipe = (props) => {
  const groupRef = useRef();
  const { nodes, materials } = useGLTF(warpPipeScene);

  // Set overall model scale here
  const overallScale = [5, 5, 5];

  return (
    <group ref={groupRef} {...props} scale={overallScale}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Hole.geometry}
        material={materials.Black}
        scale={[0.84, 1, 0.84]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pipe.geometry}
        material={materials.Green}
        scale={[0.84, 1, 0.84]}
      />
    </group>
  );
};

useGLTF.preload(warpPipeScene);
export default warpPipe;
