/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { MeshStandardMaterial, DoubleSide } from "three";
import baseRoomScene from "../assets/3d/baseRoom.glb";
import { a } from "@react-spring/three";

const walls = new MeshStandardMaterial({
  color: "#dedbd7",
  roughness: 0.9,
  metalness: 0,
});

const underside = new MeshStandardMaterial({
  color: "#ffffff",
  roughness: 0.9,
  metalness: 0,
});

const floor = new MeshStandardMaterial({
  color: "#997e68",
  roughness: 0.9,
  metalness: 0,
});

const BaseRoom = (props) => {
  const roomRef = useRef();
  const { nodes } = useGLTF(baseRoomScene);

  return (
    <a.group {...props} ref={roomRef}>
      <group position={[0, 0, 0]}>
        <mesh
          receiveShadow
          geometry={nodes.Cube003.geometry}
          material={floor}
        />
        <mesh
          receiveShadow
          geometry={nodes.Cube003_1.geometry}
          material={underside}
        />
        <mesh
          receiveShadow
          geometry={nodes.Cube003_2.geometry}
          material={walls}
        />
      </group>
    </a.group>
  );
};

export default BaseRoom;
