/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { a } from "@react-spring/three";

import roomScene from "../assets/3d/EmptyRoom.glb";

const EmptyRoom = (props) => {
  const roomRef = useRef();
  const { nodes, materials } = useGLTF(roomScene);
  return (
    <a.group ref={roomRef} {...props}>
      <group position={[0, 0.064, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials.wall2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_1.geometry}
          material={materials.Shop}
        />
      </group>
    </a.group>
  );
};

export default EmptyRoom;
