/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: LowPolyBoy (https://sketchfab.com/lowPolyBoy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-isometric-cafe-a945f20219c44e94a77cf76929368470
Title: (FREE) Isometric Cafe
*/

import { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { a } from "@react-spring/three";

import cafeScene from "../assets/3d/free_isometric_cafe.glb";

const PlaceholderCafe = (props) => {
  const cafeRef = useRef();
  const { nodes, materials } = useGLTF(cafeScene);
  return (
    <a.group ref={cafeRef} {...props}>
      <group position={[0, 0, 0]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.wall2} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Shop} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Menu} />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.Emmision}
        />
        <group position={[0.742, 0.946, -0.479]}>
          <mesh
            geometry={nodes.Object_9.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            geometry={nodes.Object_11.geometry}
            material={materials.tbjr_material}
            position={[-0.049, 0.002, 0.046]}
            rotation={[0, -0.392, 0]}
          />
          <mesh
            geometry={nodes.Object_13.geometry}
            material={materials.tbjr_material}
            position={[-0.053, 0.002, -0.053]}
            rotation={[0, -0.392, 0]}
          />
          <mesh
            geometry={nodes.Object_15.geometry}
            material={materials.tbjr_material}
            position={[0.059, 0.002, 0.046]}
            rotation={[0, -0.392, 0]}
          />
          <mesh
            geometry={nodes.Object_17.geometry}
            material={materials.material_0}
            position={[0.055, 0.002, -0.053]}
            rotation={[0, -0.392, 0]}
          />
          <mesh
            geometry={nodes.Object_19.geometry}
            material={materials.tbjr_material}
            position={[-0.049, 0.041, 0.046]}
            rotation={[0.165, -0.969, -0.017]}
          />
          <mesh
            geometry={nodes.Object_21.geometry}
            material={materials.tbjr_material}
            position={[-0.053, 0.038, -0.053]}
            rotation={[-0.231, -0.35, -0.2]}
          />
          <mesh
            geometry={nodes.Object_23.geometry}
            material={materials.tbjr_material}
            position={[0.059, 0.041, 0.046]}
            rotation={[0.149, -0.293, 0.042]}
          />
          <mesh
            geometry={nodes.Object_25.geometry}
            material={materials.tbjr_material}
            position={[0.055, 0.041, -0.053]}
            rotation={[-0.173, 0.438, 0.042]}
          />
        </group>
        <group position={[-0.583, 0.749, -0.861]}>
          <mesh geometry={nodes.Object_27.geometry} material={materials.Shop} />
          <group position={[0, -0.009, -0.058]}>
            <mesh
              geometry={nodes.Object_29.geometry}
              material={materials.Wood}
            />
            <mesh
              geometry={nodes.Object_30.geometry}
              material={materials.Emmision}
            />
            <mesh
              geometry={nodes.Object_31.geometry}
              material={materials.Shop}
            />
          </group>
        </group>
        <group position={[0.024, 1.514, -0.837]} rotation={[0, 0.1, 0]}>
          <mesh
            geometry={nodes.Object_33.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            geometry={nodes.Object_35.geometry}
            material={materials.tbjr_material}
            position={[0.237, 0, 0.113]}
            rotation={[0, -0.21, 0]}
          />
          <mesh
            geometry={nodes.Object_37.geometry}
            material={materials.tbjr_material}
            position={[0.241, 0, 0.024]}
            rotation={[0, -0.253, 0]}
          />
          <mesh
            geometry={nodes.Object_39.geometry}
            material={materials.tbjr_material}
            position={[0.116, 0, 0.1]}
            rotation={[0, 0.001, 0]}
          />
          <mesh
            geometry={nodes.Object_41.geometry}
            material={materials.tbjr_material}
            position={[0.124, 0, 0.013]}
            rotation={[0, -0.1, 0]}
          />
          <mesh
            geometry={nodes.Object_43.geometry}
            material={materials.tbjr_material}
            position={[-0.009, 0, 0.088]}
            rotation={[0, -0.216, 0]}
          />
        </group>
        <group position={[0.74, 0.424, 0.384]} rotation={[0, 1.523, 0]}>
          <mesh
            geometry={nodes.Object_45.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            geometry={nodes.Object_47.geometry}
            material={materials.tbjr_material}
            position={[-0.202, 0.383, 0.037]}
            rotation={[0, -1.523, 0]}
          />
          <mesh
            geometry={nodes.Object_49.geometry}
            material={materials.tbjr_material}
            position={[0.007, 0.383, 0]}
            rotation={[0, 0.048, 0]}
          />
          <mesh
            geometry={nodes.Object_51.geometry}
            material={materials.tbjr_material}
            position={[-0.018, 0.19, 0.001]}
            rotation={[0, 0.112, 0]}
          />
          <mesh
            geometry={nodes.Object_53.geometry}
            material={materials.tbjr_material}
            position={[-0.126, 0.19, 0.006]}
            rotation={[0, -0.055, 0]}
          />
          <mesh
            geometry={nodes.Object_55.geometry}
            material={materials.tbjr_material}
            position={[-0.234, 0.19, 0.012]}
            rotation={[0, -0.004, 0]}
          />
          <mesh
            geometry={nodes.Object_57.geometry}
            material={materials.tbjr_material}
            position={[-0.114, 0, 0.006]}
            rotation={[0, 0.223, 0]}
          />
          <mesh
            geometry={nodes.Object_59.geometry}
            material={materials.tbjr_material}
            position={[-0.233, 0, 0.011]}
            rotation={[0, -0.081, 0]}
          />
          <mesh
            geometry={nodes.Object_61.geometry}
            material={materials.tbjr_material}
            position={[-0.076, 0.359, -0.005]}
            rotation={[0, -1.523, 0]}
          />
          <mesh
            geometry={nodes.Object_63.geometry}
            material={materials.tbjr_material}
            position={[-0.191, 0.352, -0.054]}
            rotation={[0, -0.198, 0]}
          />
          <mesh
            geometry={nodes.Object_65.geometry}
            material={materials.tbjr_material}
            position={[-0.005, -0.243, 0.003]}
            rotation={[0, -1.243, 0]}
          />
          <mesh
            geometry={nodes.Object_67.geometry}
            material={materials.tbjr_material}
            position={[-0.118, -0.243, 0.059]}
            rotation={[-Math.PI, 0.228, -Math.PI]}
          />
          <mesh
            geometry={nodes.Object_69.geometry}
            material={materials.tbjr_material}
            position={[-0.19, -0.243, -0.03]}
            rotation={[-Math.PI, -0.188, -Math.PI]}
          />
        </group>
        <group position={[-0.858, 0.546, 0.854]}>
          <mesh
            geometry={nodes.Object_71.geometry}
            material={materials.tbjr_material}
          />
          <group
            position={[-0.037, 0.027, -0.702]}
            rotation={[0, -0.392, 0]}
            scale={[1.717, 1, 1.717]}
          >
            <mesh
              geometry={nodes.Object_87.geometry}
              material={materials.tbjr_material}
            />
            <mesh
              geometry={nodes.Object_89.geometry}
              material={materials.tbjr_material}
              position={[0.004, 0.029, 0.001]}
              rotation={[-Math.PI, 0.586, -Math.PI]}
              scale={[0.752, 1.291, 0.752]}
            />
          </group>
          <group
            position={[-0.003, 0.027, -0.222]}
            rotation={[0, -0.392, 0]}
            scale={[1.717, 1, 1.717]}
          >
            <mesh
              geometry={nodes.Object_91.geometry}
              material={materials.tbjr_material}
            />
            <mesh
              geometry={nodes.Object_93.geometry}
              material={materials.tbjr_material}
              position={[-0.009, 0.024, -0.017]}
              rotation={[0.272, 0.376, -0.079]}
              scale={[0.583, 0.983, 0.61]}
            />
            <mesh
              geometry={nodes.Object_95.geometry}
              material={materials.tbjr_material}
              position={[0.011, 0.024, 0.018]}
              rotation={[2.869, -0.376, 3.063]}
              scale={[0.583, 0.983, 0.61]}
            />
          </group>
          <mesh
            geometry={nodes.Object_73.geometry}
            material={materials.tbjr_material}
            position={[0.274, -0.255, 0.037]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes.Object_75.geometry}
            material={materials.tbjr_material}
            position={[-0.021, -0.202, -1.159]}
          />
          <mesh
            geometry={nodes.Object_77.geometry}
            material={materials.tbjr_material}
            position={[0.139, -0.202, -0.69]}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes.Object_79.geometry}
            material={materials.tbjr_material}
            position={[0.14, -0.202, -0.286]}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes.Object_81.geometry}
            material={materials.tbjr_material}
            position={[0.492, -0.202, 0.023]}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes.Object_83.geometry}
            material={materials.tbjr_material}
            position={[0.016, 0.027, -0.583]}
            rotation={[-Math.PI, 0.639, -Math.PI]}
          />
          <mesh
            geometry={nodes.Object_85.geometry}
            material={materials.tbjr_material}
            position={[-0.053, 0.027, -0.355]}
            rotation={[0, -0.859, 0]}
          />
        </group>
        <group position={[0.493, 1.168, -0.792]}>
          <mesh
            geometry={nodes.Object_101.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            geometry={nodes.Object_103.geometry}
            material={materials.tbjr_material}
            position={[0.002, 0.061, 0.039]}
          />
          <mesh
            geometry={nodes.Object_105.geometry}
            material={materials.tbjr_material}
            position={[0.04, 0.061, -0.021]}
            rotation={[0, -0.959, 0]}
          />
          <mesh
            geometry={nodes.Object_107.geometry}
            material={materials.tbjr_material}
            position={[-0.037, 0.061, -0.024]}
            rotation={[0, 0.913, 0]}
          />
          <mesh
            geometry={nodes.Object_109.geometry}
            material={materials.tbjr_material}
            position={[0.036, 0.093, 0.019]}
            rotation={[0, 1.015, 0]}
          />
          <mesh
            geometry={nodes.Object_111.geometry}
            material={materials.tbjr_material}
            position={[0.006, 0.093, -0.045]}
            rotation={[0, 0.056, 0]}
          />
          <mesh
            geometry={nodes.Object_113.geometry}
            material={materials.tbjr_material}
            position={[-0.037, 0.093, 0.019]}
            rotation={[-Math.PI, 1.214, -Math.PI]}
          />
          <mesh
            geometry={nodes.Object_115.geometry}
            material={materials.tbjr_material}
            position={[0.024, 0.126, 0.005]}
            rotation={[0, 1.321, 0]}
          />
          <mesh
            geometry={nodes.Object_117.geometry}
            material={materials.tbjr_material}
            position={[-0.023, 0.126, -0.007]}
            rotation={[0, 1.321, 0]}
          />
        </group>
        <group position={[-0.372, 1.543, -0.756]}>
          <mesh
            geometry={nodes.Object_119.geometry}
            material={materials.gradient_glossy}
          />
          <mesh
            geometry={nodes.Object_121.geometry}
            material={materials.tbjr_material}
            position={[-0.378, 0.037, -0.001]}
            rotation={[0, 0.288, 0]}
          />
          <mesh
            geometry={nodes.Object_123.geometry}
            material={materials.tbjr_material}
            position={[-0.281, 0.029, 0.022]}
            rotation={[0, -0.032, 0]}
          />
          <mesh
            geometry={nodes.Object_125.geometry}
            material={materials.tbjr_material}
            position={[-0.005, 0.195, 0.004]}
            rotation={[0, -0.237, 0]}
          />
          <mesh
            geometry={nodes.Object_127.geometry}
            material={materials.tbjr_material}
            position={[-0.11, 0.195, 0.005]}
            rotation={[0, 0.13, 0]}
          />
          <mesh
            geometry={nodes.Object_129.geometry}
            material={materials.tbjr_material}
            position={[-0.009, 0.195, -0.071]}
            rotation={[0, 0.106, 0]}
          />
          <mesh
            geometry={nodes.Object_131.geometry}
            material={materials.tbjr_material}
            position={[-0.102, 0.195, -0.071]}
            rotation={[0, -0.179, 0]}
          />
          <mesh
            geometry={nodes.Object_133.geometry}
            material={materials.gradient_glossy}
            position={[-0.096, 0, 0]}
            rotation={[0, -0.317, 0]}
          />
          <mesh
            geometry={nodes.Object_135.geometry}
            material={materials.gradient_glossy}
            position={[-0.191, 0, 0]}
            rotation={[0, 0.301, 0]}
          />
          <mesh
            geometry={nodes.Object_137.geometry}
            material={materials.gradient_glossy}
            position={[-0.307, 0.166, -0.011]}
            rotation={[0, -0.52, 0]}
          />
          <mesh
            geometry={nodes.Object_139.geometry}
            material={materials.gradient_glossy}
            position={[-0.401, 0.166, -0.011]}
            rotation={[0, 0.301, 0]}
          />
          <mesh
            geometry={nodes.Object_141.geometry}
            material={materials.gradient_glossy}
            position={[-0.205, 0.166, -0.011]}
            rotation={[0, -0.046, 0]}
          />
        </group>
        <group
          position={[0.756, 1.172, 0.432]}
          rotation={[Math.PI, -1.149, Math.PI]}
        >
          <mesh
            geometry={nodes.Object_149.geometry}
            material={materials.gradient_glossy}
          />
          <mesh
            geometry={nodes.Object_151.geometry}
            material={materials.tbjr_material}
            position={[-0.012, 0.175, 0.014]}
            rotation={[0, 0.39, 0]}
          />
          <mesh
            geometry={nodes.Object_153.geometry}
            material={materials.tbjr_material}
            position={[0.083, 0.175, -0.03]}
            rotation={[0, 0.517, 0]}
          />
          <mesh
            geometry={nodes.Object_155.geometry}
            material={materials.tbjr_material}
            position={[0.212, 0.321, -0.105]}
            rotation={[0, 0.39, 0]}
          />
          <mesh
            geometry={nodes.Object_157.geometry}
            material={materials.tbjr_material}
            position={[0.307, 0.321, -0.15]}
            rotation={[0, 0.517, 0]}
          />
          <mesh
            geometry={nodes.Object_159.geometry}
            material={materials.gradient_glossy}
            position={[0.185, 0.145, -0.083]}
            rotation={[0, 0.586, 0]}
          />
          <mesh
            geometry={nodes.Object_161.geometry}
            material={materials.gradient_glossy}
            position={[0.282, 0.145, -0.127]}
            rotation={[0, 0.052, 0]}
          />
          <mesh
            geometry={nodes.Object_163.geometry}
            material={materials.gradient_glossy}
            position={[0.282, 0, -0.127]}
            rotation={[0, 0.052, 0]}
          />
          <mesh
            geometry={nodes.Object_165.geometry}
            material={materials.gradient_glossy}
            position={[0.189, 0, -0.085]}
            rotation={[0, 0.052, 0]}
          />
          <mesh
            geometry={nodes.Object_167.geometry}
            material={materials.gradient_glossy}
            position={[0.095, 0, -0.042]}
            rotation={[0, 0.773, 0]}
          />
          <mesh
            geometry={nodes.Object_169.geometry}
            material={materials.gradient_glossy}
            position={[-0.02, 0.272, 0.036]}
            rotation={[0, 0.586, 0]}
          />
          <mesh
            geometry={nodes.Object_171.geometry}
            material={materials.gradient_glossy}
            position={[0.024, 0.272, 0.016]}
            rotation={[0, 0.052, 0]}
          />
          <mesh
            geometry={nodes.Object_173.geometry}
            material={materials.gradient_glossy}
            position={[0.08, 0.272, -0.009]}
            rotation={[0, 0.586, 0]}
          />
          <mesh
            geometry={nodes.Object_175.geometry}
            material={materials.gradient_glossy}
            position={[0.124, 0.272, -0.029]}
            rotation={[0, 0.052, 0]}
          />
          <mesh
            geometry={nodes.Object_177.geometry}
            material={materials.gradient_glossy}
            position={[-0.034, 0.291, -0.041]}
            rotation={[0, 0.474, 0]}
          />
          <mesh
            geometry={nodes.Object_179.geometry}
            material={materials.gradient_glossy}
            position={[0.056, 0.291, -0.082]}
            rotation={[0, 0.16, 0]}
          />
        </group>
        <group position={[-0.111, 0.663, -0.698]}>
          <mesh
            geometry={nodes.Object_181.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            geometry={nodes.Object_183.geometry}
            material={materials.tbjr_material}
            position={[0, 0.1, 0]}
          />
        </group>
        <group position={[0.099, 0.663, -0.698]}>
          <mesh
            geometry={nodes.Object_185.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            geometry={nodes.Object_187.geometry}
            material={materials.tbjr_material}
            position={[-0.036, 0.111, -0.005]}
            rotation={[0.011, 0.575, -0.103]}
          />
          <mesh
            geometry={nodes.Object_189.geometry}
            material={materials.tbjr_material}
            position={[0.024, 0.111, 0.062]}
            rotation={[0.023, 1.149, -0.118]}
          />
        </group>
        <group position={[0.307, 0.663, -0.698]}>
          <mesh
            geometry={nodes.Object_191.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            geometry={nodes.Object_193.geometry}
            material={materials.tbjr_material}
            position={[-0.042, 0.104, 0.027]}
            rotation={[-0.378, 0.568, 0.788]}
          />
          <mesh
            geometry={nodes.Object_195.geometry}
            material={materials.tbjr_material}
            position={[-0.024, 0.096, -0.052]}
            rotation={[0.23, 0.606, -0.087]}
          />
          <mesh
            geometry={nodes.Object_197.geometry}
            material={materials.tbjr_material}
            position={[0.063, 0.097, 0.009]}
            rotation={[-0.313, 0.652, 0.455]}
          />
          <mesh
            geometry={nodes.Object_199.geometry}
            material={materials.tbjr_material}
            position={[0.008, 0.104, 0.049]}
            rotation={[Math.PI, 1.405, -2.424]}
          />
        </group>
        <group
          position={[0.007, 0.761, 0.106]}
          rotation={[Math.PI, -1.463, Math.PI]}
        >
          <mesh
            geometry={nodes.Object_203.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            geometry={nodes.Object_205.geometry}
            material={materials.tbjr_material}
            position={[-0.024, 0.108, -0.016]}
            rotation={[0.011, 0.575, -0.103]}
            scale={0.86}
          />
          <mesh
            geometry={nodes.Object_207.geometry}
            material={materials.tbjr_material}
            position={[0.028, 0.108, 0.041]}
            rotation={[0.023, 1.149, -0.118]}
            scale={0.86}
          />
        </group>
        <group position={[-0.052, 1.136, -0.792]}>
          <mesh
            geometry={nodes.Object_209.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            geometry={nodes.Object_210.geometry}
            material={materials.material_0}
          />
          <mesh
            geometry={nodes.Object_212.geometry}
            material={materials.tbjr_material}
            position={[0.052, 0.048, -0.038]}
          />
          <mesh
            geometry={nodes.Object_214.geometry}
            material={materials.tbjr_material}
            position={[0.047, 0.048, 0.027]}
          />
          <mesh
            geometry={nodes.Object_216.geometry}
            material={materials.tbjr_material}
            position={[-0.047, 0.048, -0.034]}
          />
          <mesh
            geometry={nodes.Object_218.geometry}
            material={materials.tbjr_material}
            position={[-0.07, 0.073, 0.04]}
            rotation={[-0.135, 0.683, -0.211]}
          />
          <mesh
            geometry={nodes.Object_220.geometry}
            material={materials.tbjr_material}
            position={[0.008, 0.082, 0.042]}
            rotation={[0.127, 0.358, -0.112]}
          />
          <mesh
            geometry={nodes.Object_222.geometry}
            material={materials.tbjr_material}
            position={[0.003, 0.08, -0.031]}
            rotation={[-0.007, -0.241, -0.011]}
          />
          <mesh
            geometry={nodes.Object_224.geometry}
            material={materials.tbjr_material}
            position={[0, 0.046, 0]}
          />
        </group>
        <group position={[0.196, 1.136, -0.792]}>
          <mesh
            geometry={nodes.Object_226.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            geometry={nodes.Object_227.geometry}
            material={materials.material_0}
          />
          <mesh
            geometry={nodes.Object_229.geometry}
            material={materials.tbjr_material}
            position={[0, 0.046, 0]}
          />
          <mesh
            geometry={nodes.Object_231.geometry}
            material={materials.tbjr_material}
            position={[0, 0.06, 0.014]}
          />
          <mesh
            geometry={nodes.Object_233.geometry}
            material={materials.tbjr_material}
            position={[-0.056, 0.087, -0.01]}
            rotation={[2.097, -0.701, 2.236]}
          />
          <mesh
            geometry={nodes.Object_235.geometry}
            material={materials.tbjr_material}
            position={[0.052, 0.092, -0.01]}
            rotation={[2.049, 0.732, -2.298]}
          />
        </group>
        <group position={[0.73, 1.182, -0.792]}>
          <mesh
            geometry={nodes.Object_237.geometry}
            material={materials.tbjr_material}
          />
          <group position={[0, -0.046, 0]}>
            <mesh
              geometry={nodes.Object_251.geometry}
              material={materials.tbjr_material}
            />
            <mesh
              geometry={nodes.Object_252.geometry}
              material={materials.material_0}
            />
          </group>
          <mesh
            geometry={nodes.Object_239.geometry}
            material={materials.tbjr_material}
            position={[0.052, 0.001, -0.038]}
          />
          <mesh
            geometry={nodes.Object_241.geometry}
            material={materials.tbjr_material}
            position={[0.047, 0.001, 0.027]}
          />
          <mesh
            geometry={nodes.Object_243.geometry}
            material={materials.tbjr_material}
            position={[-0.047, 0.001, -0.034]}
          />
          <mesh
            geometry={nodes.Object_245.geometry}
            material={materials.tbjr_material}
            position={[-0.07, 0.027, 0.04]}
            rotation={[-0.135, 0.683, -0.211]}
          />
          <mesh
            geometry={nodes.Object_247.geometry}
            material={materials.tbjr_material}
            position={[0.008, 0.036, 0.042]}
            rotation={[0.127, 0.358, -0.112]}
          />
          <mesh
            geometry={nodes.Object_249.geometry}
            material={materials.tbjr_material}
            position={[0.003, 0.034, -0.031]}
            rotation={[-0.007, -0.241, -0.011]}
          />
        </group>
        <group position={[0.73, 1.429, -0.792]}>
          <mesh
            geometry={nodes.Object_254.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            geometry={nodes.Object_255.geometry}
            material={materials.material_0}
          />
          <mesh
            geometry={nodes.Object_257.geometry}
            material={materials.tbjr_material}
            position={[0.058, 0.052, 0]}
            rotation={[0, -0.057, 0]}
          />
          <mesh
            geometry={nodes.Object_259.geometry}
            material={materials.tbjr_material}
            position={[-0.015, 0.052, 0]}
            rotation={[0, 0.06, 0]}
          />
          <mesh
            geometry={nodes.Object_261.geometry}
            material={materials.tbjr_material}
            position={[-0.287, 0.052, 0]}
            rotation={[0, -0.038, 0]}
          />
          <mesh
            geometry={nodes.Object_263.geometry}
            material={materials.tbjr_material}
            position={[-0.118, 0.052, -0.034]}
            rotation={[-Math.PI, 1.548, -Math.PI]}
          />
          <mesh
            geometry={nodes.Object_265.geometry}
            material={materials.tbjr_material}
            position={[-0.117, 0.052, 0.033]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes.Object_267.geometry}
            material={materials.tbjr_material}
            position={[-0.217, 0.052, 0]}
          />
        </group>
        <group position={[0.082, 0.602, 0.236]}>
          <mesh
            geometry={nodes.Object_269.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            geometry={nodes.Object_270.geometry}
            material={materials.material_0}
          />
          <mesh
            geometry={nodes.Object_272.geometry}
            material={materials.tbjr_material}
            position={[-0.241, 0.027, -0.034]}
          />
          <mesh
            geometry={nodes.Object_274.geometry}
            material={materials.tbjr_material}
            position={[-0.166, 0.027, -0.034]}
            rotation={[0, -0.809, 0]}
          />
          <mesh
            geometry={nodes.Object_276.geometry}
            material={materials.tbjr_material}
            position={[-0.241, 0.027, 0.034]}
            rotation={[0, -0.945, 0]}
          />
          <mesh
            geometry={nodes.Object_278.geometry}
            material={materials.tbjr_material}
            position={[-0.166, 0.027, 0.034]}
            rotation={[0, 0.634, 0]}
          />
          <mesh
            geometry={nodes.Object_280.geometry}
            material={materials.tbjr_material}
            position={[-0.095, 0.027, -0.034]}
            rotation={[0, -0.809, 0]}
          />
          <mesh
            geometry={nodes.Object_282.geometry}
            material={materials.tbjr_material}
            position={[-0.095, 0.027, 0.034]}
            rotation={[0, 0.634, 0]}
          />
        </group>
        <group position={[0.082, 0.602, 0.411]}>
          <mesh
            geometry={nodes.Object_284.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            geometry={nodes.Object_285.geometry}
            material={materials.material_0}
          />
          <mesh
            geometry={nodes.Object_287.geometry}
            material={materials.tbjr_material}
            position={[-0.238, 0.029, 0.033]}
            rotation={[0, -0.772, 0]}
          />
          <mesh
            geometry={nodes.Object_289.geometry}
            material={materials.tbjr_material}
            position={[-0.171, 0.029, -0.032]}
            rotation={[0, -0.459, 0]}
          />
          <mesh
            geometry={nodes.Object_291.geometry}
            material={materials.tbjr_material}
            position={[-0.171, 0.029, 0.033]}
            rotation={[0, 0.399, 0]}
          />
          <mesh
            geometry={nodes.Object_293.geometry}
            material={materials.tbjr_material}
            position={[-0.238, 0.029, -0.032]}
            rotation={[0, 0.333, 0]}
          />
          <mesh
            geometry={nodes.Object_295.geometry}
            material={materials.tbjr_material}
            position={[-0.106, 0.029, -0.032]}
            rotation={[0, 0.464, 0]}
          />
          <mesh
            geometry={nodes.Object_297.geometry}
            material={materials.tbjr_material}
            position={[-0.106, 0.029, 0.033]}
            rotation={[0, -0.085, 0]}
          />
        </group>
        <group position={[0.082, 0.602, 0.057]}>
          <mesh
            geometry={nodes.Object_299.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            geometry={nodes.Object_300.geometry}
            material={materials.material_0}
          />
          <mesh
            geometry={nodes.Object_302.geometry}
            material={materials.tbjr_material}
            position={[-0.218, 0.03, -0.027]}
          />
          <mesh
            geometry={nodes.Object_304.geometry}
            material={materials.tbjr_material}
            position={[-0.156, 0.03, 0.024]}
          />
          <mesh
            geometry={nodes.Object_306.geometry}
            material={materials.tbjr_material}
            position={[-0.226, 0.048, 0.033]}
            rotation={[0.871, -0.736, 0.468]}
          />
          <mesh
            geometry={nodes.Object_308.geometry}
            material={materials.tbjr_material}
            position={[-0.099, 0.03, -0.03]}
          />
        </group>
        <group position={[0.082, 0.383, 0.41]}>
          <mesh
            geometry={nodes.Object_310.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            geometry={nodes.Object_311.geometry}
            material={materials.material_0}
          />
          <mesh
            geometry={nodes.Object_313.geometry}
            material={materials.tbjr_material}
            position={[-0.241, 0.027, -0.034]}
          />
          <mesh
            geometry={nodes.Object_315.geometry}
            material={materials.tbjr_material}
            position={[-0.166, 0.027, -0.034]}
            rotation={[0, -0.809, 0]}
          />
          <mesh
            geometry={nodes.Object_317.geometry}
            material={materials.tbjr_material}
            position={[-0.241, 0.027, 0.034]}
            rotation={[0, -0.945, 0]}
          />
          <mesh
            geometry={nodes.Object_319.geometry}
            material={materials.tbjr_material}
            position={[-0.166, 0.027, 0.034]}
            rotation={[0, 0.634, 0]}
          />
          <mesh
            geometry={nodes.Object_321.geometry}
            material={materials.tbjr_material}
            position={[-0.095, 0.027, -0.034]}
            rotation={[0, -0.809, 0]}
          />
          <mesh
            geometry={nodes.Object_323.geometry}
            material={materials.tbjr_material}
            position={[-0.095, 0.027, 0.034]}
            rotation={[0, 0.634, 0]}
          />
        </group>
        <group position={[0.082, 0.383, 0.236]}>
          <mesh
            geometry={nodes.Object_325.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            geometry={nodes.Object_326.geometry}
            material={materials.material_0}
          />
          <mesh
            geometry={nodes.Object_328.geometry}
            material={materials.tbjr_material}
            position={[-0.235, 0.022, 0.036]}
          />
          <mesh
            geometry={nodes.Object_330.geometry}
            material={materials.tbjr_material}
            position={[-0.192, 0.022, -0.022]}
            rotation={[-Math.PI, 1.235, -Math.PI]}
          />
          <mesh
            geometry={nodes.Object_332.geometry}
            material={materials.tbjr_material}
            position={[-0.148, 0.022, 0.037]}
            rotation={[0, 0.691, 0]}
          />
          <mesh
            geometry={nodes.Object_334.geometry}
            material={materials.tbjr_material}
            position={[-0.106, 0.022, -0.022]}
            rotation={[0, 0.746, 0]}
          />
        </group>
        <group position={[0.082, 0.383, 0.057]}>
          <mesh
            geometry={nodes.Object_336.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            geometry={nodes.Object_337.geometry}
            material={materials.material_0}
          />
          <mesh
            geometry={nodes.Object_339.geometry}
            material={materials.tbjr_material}
            position={[-0.236, 0.03, -0.031]}
          />
          <mesh
            geometry={nodes.Object_341.geometry}
            material={materials.tbjr_material}
            position={[-0.236, 0.03, 0.034]}
          />
          <mesh
            geometry={nodes.Object_343.geometry}
            material={materials.tbjr_material}
            position={[-0.168, 0.03, -0.031]}
          />
          <mesh
            geometry={nodes.Object_345.geometry}
            material={materials.tbjr_material}
            position={[-0.168, 0.03, 0.034]}
          />
          <mesh
            geometry={nodes.Object_347.geometry}
            material={materials.tbjr_material}
            position={[-0.098, 0.03, -0.031]}
          />
          <mesh
            geometry={nodes.Object_349.geometry}
            material={materials.tbjr_material}
            position={[-0.098, 0.03, 0.034]}
          />
        </group>
        <group position={[0.082, 0.166, 0.235]}>
          <mesh
            geometry={nodes.Object_351.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            geometry={nodes.Object_352.geometry}
            material={materials.material_0}
          />
          <mesh
            geometry={nodes.Object_354.geometry}
            material={materials.tbjr_material}
            position={[-0.236, 0.03, -0.031]}
          />
          <mesh
            geometry={nodes.Object_356.geometry}
            material={materials.tbjr_material}
            position={[-0.236, 0.03, 0.034]}
          />
          <mesh
            geometry={nodes.Object_358.geometry}
            material={materials.tbjr_material}
            position={[-0.168, 0.03, -0.031]}
          />
          <mesh
            geometry={nodes.Object_360.geometry}
            material={materials.tbjr_material}
            position={[-0.168, 0.03, 0.034]}
          />
          <mesh
            geometry={nodes.Object_362.geometry}
            material={materials.tbjr_material}
            position={[-0.098, 0.03, -0.031]}
          />
          <mesh
            geometry={nodes.Object_364.geometry}
            material={materials.tbjr_material}
            position={[-0.098, 0.03, 0.034]}
          />
        </group>
        <group position={[0.082, 0.166, 0.41]}>
          <mesh
            geometry={nodes.Object_366.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            geometry={nodes.Object_367.geometry}
            material={materials.material_0}
          />
          <mesh
            geometry={nodes.Object_369.geometry}
            material={materials.tbjr_material}
            position={[-0.218, 0.03, -0.027]}
          />
          <mesh
            geometry={nodes.Object_371.geometry}
            material={materials.tbjr_material}
            position={[-0.156, 0.03, 0.024]}
          />
          <mesh
            geometry={nodes.Object_373.geometry}
            material={materials.tbjr_material}
            position={[-0.226, 0.048, 0.033]}
            rotation={[0.871, -0.736, 0.468]}
          />
          <mesh
            geometry={nodes.Object_375.geometry}
            material={materials.tbjr_material}
            position={[-0.099, 0.03, -0.03]}
          />
        </group>
        <group position={[0.082, 0.165, 0.058]}>
          <mesh
            geometry={nodes.Object_377.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            geometry={nodes.Object_378.geometry}
            material={materials.material_0}
          />
          <mesh
            geometry={nodes.Object_380.geometry}
            material={materials.tbjr_material}
            position={[-0.238, 0.029, -0.032]}
            rotation={[0, 0.333, 0]}
          />
          <mesh
            geometry={nodes.Object_382.geometry}
            material={materials.tbjr_material}
            position={[-0.238, 0.029, 0.033]}
            rotation={[0, -0.772, 0]}
          />
          <mesh
            geometry={nodes.Object_384.geometry}
            material={materials.tbjr_material}
            position={[-0.171, 0.029, -0.032]}
            rotation={[0, -0.459, 0]}
          />
          <mesh
            geometry={nodes.Object_386.geometry}
            material={materials.tbjr_material}
            position={[-0.171, 0.029, 0.033]}
            rotation={[0, 0.399, 0]}
          />
          <mesh
            geometry={nodes.Object_388.geometry}
            material={materials.tbjr_material}
            position={[-0.106, 0.029, -0.032]}
            rotation={[0, 0.464, 0]}
          />
          <mesh
            geometry={nodes.Object_390.geometry}
            material={materials.tbjr_material}
            position={[-0.106, 0.029, 0.033]}
            rotation={[0, -0.085, 0]}
          />
        </group>
        <group position={[0.854, 1.894, -0.886]}>
          <mesh
            geometry={nodes.Object_392.geometry}
            material={materials.Shop}
          />
          <group position={[0, -0.231, 0.92]}>
            <mesh
              geometry={nodes.Object_394.geometry}
              material={materials.Shop}
            />
            <mesh
              geometry={nodes.Object_395.geometry}
              material={materials.Emmision}
            />
          </group>
          <group position={[0, -0.175, 1.085]}>
            <mesh
              geometry={nodes.Object_397.geometry}
              material={materials.Shop}
            />
            <mesh
              geometry={nodes.Object_398.geometry}
              material={materials.Emmision}
            />
          </group>
          <group position={[0, -0.097, 1.24]}>
            <mesh
              geometry={nodes.Object_400.geometry}
              material={materials.Shop}
            />
            <mesh
              geometry={nodes.Object_401.geometry}
              material={materials.Emmision}
            />
          </group>
          <group position={[0, -0.18, 1.426]}>
            <mesh
              geometry={nodes.Object_403.geometry}
              material={materials.Shop}
            />
            <mesh
              geometry={nodes.Object_404.geometry}
              material={materials.Emmision}
            />
          </group>
          <group position={[0, -0.197, 1.632]}>
            <mesh
              geometry={nodes.Object_406.geometry}
              material={materials.Shop}
            />
            <mesh
              geometry={nodes.Object_407.geometry}
              material={materials.Emmision}
            />
          </group>
          <group position={[0, -0.118, 1.797]}>
            <mesh
              geometry={nodes.Object_409.geometry}
              material={materials.Shop}
            />
            <mesh
              geometry={nodes.Object_410.geometry}
              material={materials.Emmision}
            />
          </group>
          <group position={[0, -0.154, 0.743]}>
            <mesh
              geometry={nodes.Object_412.geometry}
              material={materials.Shop}
            />
            <mesh
              geometry={nodes.Object_413.geometry}
              material={materials.Emmision}
            />
          </group>
          <group position={[0, -0.116, 0.557]}>
            <mesh
              geometry={nodes.Object_415.geometry}
              material={materials.Shop}
            />
            <mesh
              geometry={nodes.Object_416.geometry}
              material={materials.Emmision}
            />
          </group>
          <group position={[0, -0.21, 0.386]}>
            <mesh
              geometry={nodes.Object_418.geometry}
              material={materials.Shop}
            />
            <mesh
              geometry={nodes.Object_419.geometry}
              material={materials.Emmision}
            />
          </group>
          <group position={[0, -0.173, 0.153]}>
            <mesh
              geometry={nodes.Object_421.geometry}
              material={materials.Shop}
            />
            <mesh
              geometry={nodes.Object_422.geometry}
              material={materials.Emmision}
            />
          </group>
        </group>
        <group position={[0.007, 0.764, 0.198]} rotation={[0, Math.PI / 2, 0]}>
          <mesh
            geometry={nodes.Object_424.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            geometry={nodes.Object_425.geometry}
            material={materials.material_0}
          />
          <mesh
            geometry={nodes.Object_427.geometry}
            material={materials.tbjr_material}
            position={[-0.224, 0.029, -0.03]}
          />
          <mesh
            geometry={nodes.Object_429.geometry}
            material={materials.tbjr_material}
            position={[-0.224, 0.029, 0.032]}
          />
          <mesh
            geometry={nodes.Object_431.geometry}
            material={materials.tbjr_material}
            position={[-0.159, 0.029, -0.03]}
          />
          <mesh
            geometry={nodes.Object_433.geometry}
            material={materials.tbjr_material}
            position={[-0.159, 0.029, 0.032]}
          />
          <mesh
            geometry={nodes.Object_435.geometry}
            material={materials.tbjr_material}
            position={[-0.093, 0.029, -0.03]}
          />
          <mesh
            geometry={nodes.Object_437.geometry}
            material={materials.tbjr_material}
            position={[-0.093, 0.029, 0.032]}
          />
        </group>
        <mesh
          geometry={nodes.Object_97.geometry}
          material={materials.gradient_glossy}
          position={[0.8, 0.642, -0.029]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes.Object_99.geometry}
          material={materials.tbjr_material}
          position={[0.592, 0.652, -0.609]}
          rotation={[0, -0.336, 0.168]}
        />
        <mesh
          geometry={nodes.Object_143.geometry}
          material={materials.tbjr_material}
          position={[-0.29, 0.171, -0.532]}
          rotation={[0, 1.187, 0]}
        />
        <mesh
          geometry={nodes.Object_145.geometry}
          material={materials.tbjr_material}
          position={[-0.111, 1.495, -0.807]}
        />
        <mesh
          geometry={nodes.Object_147.geometry}
          material={materials.tbjr_material}
          position={[0.763, 0.171, 0.859]}
          rotation={[0, 1.187, 0]}
        />
        <mesh
          geometry={nodes.Object_201.geometry}
          material={materials.tbjr_material}
          position={[0.307, 0.755, -0.698]}
          rotation={[-Math.PI, 1.405, -Math.PI]}
        />
      </group>
    </a.group>
  );
};

export default PlaceholderCafe;
